version: "2"
services:
  mailserver:
    image: analogic/poste.io
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    networks:
      - reverse-proxy
    environment:
      - VIRTUAL_HOST=mail.obvu.tk
      - HTTPS=OFF
    ports:
      - 110:110
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 0025:0025
      - 995:995
    hostname: mail.obvu.tk


networks:
  reverse-proxy:
    external:
      name: reverse-proxy
